apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extensionlib.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- include "extensionlib.labels" (list .) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "extensionlib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "extensionlib.selectorLabels" . | nindent 8 }}
        {{- include "extensionlib.labels" (list .) | nindent 8 }}
        {{- range $key, $value := .Values.extraLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        oneagent.dynatrace.com/injection: "false"
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: extension
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            {{- include "extensionlib.deployment.env" (list .) | nindent 12 }}
            - name: STEADYBIT_EXTENSION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "datadog.secret.name" . }}
                  key: api-key
            - name: STEADYBIT_EXTENSION_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "datadog.secret.name" . }}
                  key: application-key
            - name: STEADYBIT_EXTENSION_SITE_PARAMETER
              valueFrom:
                secretKeyRef:
                  name: {{ include "datadog.secret.name" . }}
                  key: site-parameter
            - name: STEADYBIT_EXTENSION_SITE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "datadog.secret.name" . }}
                  key: site-url
            {{ if .Values.testing.scheme -}}
            - name: STEADYBIT_EXTENSION_TESTING_SCHEME
              value: {{ .Values.testing.scheme }}
            {{ end }}
            {{ if .Values.testing.host -}}
            - name: STEADYBIT_EXTENSION_TESTING_HOST
              value: {{ .Values.testing.host }}
            {{ end }}
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.discovery.attributes.excludes.monitor }}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_MONITOR
              value: {{ join "," .Values.discovery.attributes.excludes.monitor | quote }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "extensionlib.deployment.volumeMounts" (list .) | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            httpGet:
              path: /health/liveness
              port: 8091
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            httpGet:
              path: /health/readiness
              port: 8091
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        {{- include "extensionlib.deployment.volumes" (list .) | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
